Controllers/BrandController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using InventoryBeginners.Data;
using InventoryBeginners.Models;
using System.Collections.Generic;
using System;
using System.Linq;
using InventoryBeginners.Interfaces;
using CodesByAniz.Tools;
using Microsoft.AspNetCore.Authorization;

namespace InventoryBeginners.Controllers
{
    [Authorize]
    public class BrandController : Controller
    {

        private readonly IBrand _Repo;
        public BrandController(IBrand repo) // here the repository will be passed by the dependency injection.
        {
            _Repo = repo;
        }


        public IActionResult Index(string sortExpression = "", string SearchText = "", int pg = 1, int pageSize = 5)
        {
            SortModel sortModel = new SortModel();
            sortModel.AddColumn("name");
            sortModel.AddColumn("description");
            sortModel.ApplySort(sortExpression);
            ViewData["sortModel"] = sortModel;

            ViewBag.SearchText = SearchText;

            PaginatedList<Brand> items = _Repo.GetItems(sortModel.SortedProperty, sortModel.SortedOrder, SearchText, pg, pageSize);


            var pager = new PagerModel(items.TotalRecords, pg, pageSize);
            pager.SortExpression = sortExpression;
            this.ViewBag.Pager = pager;


            TempData["CurrentPage"] = pg;


            return View(items);
        }


        public IActionResult Create()
        {
            Brand item = new Brand();
            return View(item);
        }

        [HttpPost]
        public IActionResult Create(Brand item)
        {
            bool bolret = false;
            string errMessage = "";
            try
            {
                if (item.Description.Length < 4 || item.Description == null)
                    errMessage = "Description Must be atleast 4 Characters";

                if (_Repo.IsItemExists(item.Name) == true)
                    errMessage = errMessage + " " + " Name " + item.Name + " Exists Already";

                if (errMessage == "")
                {
                    item = _Repo.Create(item);
                    bolret = true;
                }
            }
            catch (Exception ex)
            {
                errMessage = errMessage + " " + ex.Message;
            }
            if (bolret == false)
            {
                TempData["ErrorMessage"] = errMessage;
                ModelState.AddModelError("", errMessage);
                return View(item);
            }
            else
            {
                TempData["SuccessMessage"] = "" + item.Name + " Created Successfully";
                return RedirectToAction(nameof(Index));
            }
        }

        public IActionResult Details(int id) //Read
        {
            Brand item = _Repo.GetItem(id);
            return View(item);
        }


        public IActionResult Edit(int id)
        {
            Brand item = _Repo.GetItem(id);
            TempData.Keep();
            return View(item);
        }

        [HttpPost]
        public IActionResult Edit(Brand item)
        {
            bool bolret = false;
            string errMessage = "";

            try
            {
                if (item.Description.Length < 4 || item.Description == null)
                    errMessage = "Description Must be atleast 4 Characters";

                if (_Repo.IsItemExists(item.Name, item.Id) == true)
                    errMessage = errMessage + item.Name + " Already Exists";

                if (errMessage == "")
                {
                    item = _Repo.Edit(item);
                    TempData["SuccessMessage"] = item.Name + ", Saved Successfully";
                    bolret = true;
                }
            }
            catch (Exception ex)
            {
                errMessage = errMessage + " " + ex.Message;
            }



            int currentPage = 1;
            if (TempData["CurrentPage"] != null)
                currentPage = (int)TempData["CurrentPage"];


            if (bolret == false)
            {
                TempData["ErrorMessage"] = errMessage;
                ModelState.AddModelError("", errMessage);
                return View(item);
            }
            else
                return RedirectToAction(nameof(Index), new { pg = currentPage });
        }

        public IActionResult Delete(int id)
        {
            Brand item = _Repo.GetItem(id);
            TempData.Keep();
            return View(item);
        }


        [HttpPost]
        public IActionResult Delete(Brand item)
        {
            try
            {
                item = _Repo.Delete(item);
            }
            catch (Exception ex)
            {
                string errMessage = ex.Message;
                TempData["ErrorMessage"] = errMessage;
                ModelState.AddModelError("", errMessage);
                return View(item);

            }

            int currentPage = 1;
            if (TempData["CurrentPage"] != null)
                currentPage = (int)TempData["CurrentPage"];

            TempData["SuccessMessage"] = item.Name + " Deleted Successfully";
            return RedirectToAction(nameof(Index), new { pg = currentPage });


        }


    }
}

Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using InventoryBeginners.Data;
using InventoryBeginners.Models;
using System.Collections.Generic;
using System;
using System.Linq;
using InventoryBeginners.Interfaces;
using CodesByAniz.Tools;
using Microsoft.AspNetCore.Authorization;

namespace InventoryBeginners.Controllers
{
    [Authorize]
    public class CategoryController : Controller
    {

        private readonly ICategory _Repo;
        public CategoryController(ICategory repo) // here the repository will be passed by the dependency injection.
        {
            _Repo = repo;
        }


        public IActionResult Index(string sortExpression = "", string SearchText = "", int pg = 1, int pageSize = 5)
        {
            SortModel sortModel = new SortModel();
            sortModel.AddColumn("name");
            sortModel.AddColumn("description");
            sortModel.ApplySort(sortExpression);
            ViewData["sortModel"] = sortModel;

            ViewBag.SearchText = SearchText;

            PaginatedList<Category> items = _Repo.GetItems(sortModel.SortedProperty, sortModel.SortedOrder, SearchText, pg, pageSize);


            var pager = new PagerModel(items.TotalRecords, pg, pageSize);
            pager.SortExpression = sortExpression;
            this.ViewBag.Pager = pager;


            TempData["CurrentPage"] = pg;


            return View(items);
        }


        public IActionResult Create()
        {
            Category item = new Category();
            return View(item);
        }

        [HttpPost]
        public IActionResult Create(Category item)
        {
            bool bolret = false;
            string errMessage = "";
            try
            {
                if (item.Description.Length < 4 || item.Description == null)
                    errMessage = "Description Must be atleast 4 Characters";

                if (_Repo.IsItemExists(item.Name) == true)
                    errMessage = errMessage + " " + " Name " + item.Name + " Exists Already";

                if (errMessage == "")
                {
                    item = _Repo.Create(item);
                    bolret = true;
                }
            }
            catch (Exception ex)
            {
                errMessage = errMessage + " " + ex.Message;
            }
            if (bolret == false)
            {
                TempData["ErrorMessage"] = errMessage;
                ModelState.AddModelError("", errMessage);
                return View(item);
            }
            else
            {
                TempData["SuccessMessage"] = "" + item.Name + " Created Successfully";
                return RedirectToAction(nameof(Index));
            }
        }

        public IActionResult Details(int id) //Read
        {
            Category item = _Repo.GetItem(id);
            return View(item);
        }


        public IActionResult Edit(int id)
        {
            Category item = _Repo.GetItem(id);
            TempData.Keep();
            return View(item);
        }

        [HttpPost]
        public IActionResult Edit(Category item)
        {
            bool bolret = false;
            string errMessage = "";

            try
            {
                if (item.Description.Length < 4 || item.Description == null)
                    errMessage = "Description Must be atleast 4 Characters";

                if (_Repo.IsItemExists(item.Name, item.Id) == true)
                    errMessage = errMessage +  item.Name + " Already Exists";

                if (errMessage == "")
                {
                    item = _Repo.Edit(item);
                    TempData["SuccessMessage"] = item.Name + ", Saved Successfully";
                    bolret = true;
                }
            }
            catch (Exception ex)
            {
                errMessage = errMessage + " " + ex.Message;
            }



            int currentPage = 1;
            if (TempData["CurrentPage"] != null)
                currentPage = (int)TempData["CurrentPage"];


            if (bolret == false)
            {
                TempData["ErrorMessage"] = errMessage;
                ModelState.AddModelError("", errMessage);
                return View(item);
            }
            else
                return RedirectToAction(nameof(Index), new { pg = currentPage });
        }

        public IActionResult Delete(int id)
        {
            Category item = _Repo.GetItem(id);
            TempData.Keep();
            return View(item);
        }


        [HttpPost]
        public IActionResult Delete(Category item)
        {
            try
            {
                item = _Repo.Delete(item);
            }
            catch (Exception ex)
            {
                string errMessage = ex.Message;
                TempData["ErrorMessage"] = errMessage;
                ModelState.AddModelError("", errMessage);
                return View(item);

            }

            int currentPage = 1;
            if (TempData["CurrentPage"] != null)
                currentPage = (int)TempData["CurrentPage"];

            TempData["SuccessMessage"] = item.Name + " Deleted Successfully";
            return RedirectToAction(nameof(Index), new { pg = currentPage });


        }


    }
}

Controllers/UnitController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using InventoryBeginners.Data;
using InventoryBeginners.Models;
using System.Collections.Generic;
using System;
using System.Linq;
using InventoryBeginners.Interfaces;
using CodesByAniz.Tools;
using Microsoft.AspNetCore.Authorization;

namespace InventoryBeginners.Controllers
{
    [Authorize]
    public class UnitController : Controller
    {       
        
        private readonly IUnit _unitRepo;
        public UnitController(IUnit unitrepo) // here the repository will be passed by the dependency injection.
        {            
            _unitRepo = unitrepo;
        }

      
        public IActionResult Index(string sortExpression="", string SearchText = "",int pg=1,int pageSize=5) 
        {
            SortModel sortModel = new SortModel();
            sortModel.AddColumn("name");
            sortModel.AddColumn("description");
            sortModel.ApplySort(sortExpression);
            ViewData["sortModel"] = sortModel;
            
            ViewBag.SearchText = SearchText;

            PaginatedList<Unit> units = _unitRepo.GetItems(sortModel.SortedProperty, sortModel.SortedOrder,SearchText,pg,pageSize);            
            

            var pager = new PagerModel(units.TotalRecords, pg, pageSize);
            pager.SortExpression = sortExpression;
            this.ViewBag.Pager = pager;


            TempData["CurrentPage"] = pg;


            return View(units);
        }


        public IActionResult Create()
        {
            Unit unit = new Unit();
            return View(unit);
        }

        [HttpPost]  
        public IActionResult Create(Unit unit)
        {
            bool bolret = false;
            string errMessage = "";
            try
            {
                if (unit.Description.Length < 4 || unit.Description == null)               
                    errMessage = "Unit Description Must be atleast 4 Characters";

                if (_unitRepo.IsUnitNameExists(unit.Name) == true)
                    errMessage = errMessage + " " + " Unit Name " + unit.Name +" Exists Already";

                if (errMessage == "")
                {
                    unit = _unitRepo.Create(unit);
                    bolret = true;
                }                
            }
            catch(Exception ex) 
            {
                errMessage = errMessage + " " + ex.Message;
            }
            if (bolret == false)
            {
                TempData["ErrorMessage"] = errMessage;
                ModelState.AddModelError("", errMessage);
                return View(unit);
            }
            else
            {
                TempData["SuccessMessage"] = "Unit " + unit.Name + " Created Successfully";
                return RedirectToAction(nameof(Index));
            }
        }

        public IActionResult Details(int id) //Read
        {
            Unit unit =_unitRepo.GetUnit(id);              
            return View(unit);        
        }


        public IActionResult Edit(int id)
        {
            Unit unit = _unitRepo.GetUnit(id);
            TempData.Keep();
            return View(unit);
        }  
        
        [HttpPost]
        public IActionResult Edit(Unit unit)
        {
            bool bolret = false;
            string errMessage = "";

            try
            {
                if (unit.Description.Length < 4 || unit.Description == null)                
                   errMessage = "Unit Description Must be atleast 4 Characters";

                if (_unitRepo.IsUnitNameExists(unit.Name, unit.Id) == true)
                    errMessage = errMessage + "Unit Name " + unit.Name + " Already Exists";

                if (errMessage == "")
                {
                    unit = _unitRepo.Edit(unit);
                    TempData["SuccessMessage"] = unit.Name + ", Unit Saved Successfully";
                    bolret = true;
                }
            }
            catch(Exception ex)
            {
                errMessage = errMessage + " " + ex.Message;                
            }

          

            int currentPage = 1;
            if (TempData["CurrentPage"] != null)
                currentPage = (int)TempData["CurrentPage"];

          
            if(bolret==false)
            {
                TempData["ErrorMessage"] = errMessage;
                ModelState.AddModelError("", errMessage);
                return View(unit);
            }
            else
            return RedirectToAction(nameof(Index),new {pg=currentPage});
        }

        public IActionResult Delete(int id)
        {
            Unit unit = _unitRepo.GetUnit(id);
            TempData.Keep();
            return View(unit);
        }

        
        [HttpPost]
        public IActionResult Delete(Unit unit)
        {
            try
            {
                unit = _unitRepo.Delete(unit);
            }
            catch(Exception ex)
            {
                string errMessage = ex.Message;
                TempData["ErrorMessage"] = errMessage;
                ModelState.AddModelError("", errMessage);
                return View(unit);
            }          
            
            int currentPage = 1;
            if (TempData["CurrentPage"] != null)
                currentPage = (int)TempData["CurrentPage"];

            TempData["SuccessMessage"] = "Unit " + unit.Name + " Deleted Successfully";
            return RedirectToAction(nameof(Index), new { pg = currentPage });


        }

     
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Inventory</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>

@{ 
    string menuTextColor = "text-white";   

}
<body>

    <div class="container-fluid" style="background:linear-gradient(to right,#28340B,#197696);">
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand @menuTextColor" asp-area="" asp-controller="Home" asp-action="Index">Inventory</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link @menuTextColor" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            @if (SignInManager.IsSignedIn(User))
                            {

                                <li class="dropdown nav-item pr-2">
                                    <a class="nav-link dropdown-toggle @menuTextColor" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                        Masters
                                    </a>

                                    <ul class="dropdown-menu" style="background:linear-gradient(to right,#28340B,#197696);">
                                        <li class="nav-item">
                                            <a class="nav-link @menuTextColor" asp-area="" asp-controller="Unit" asp-action="Index">Units</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link @menuTextColor" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
                                        </li>

                                        <li class="nav-item">
                                            <a class="nav-link @menuTextColor" asp-area="" asp-controller="Category" asp-action="Index">Categories</a>
                                        </li>

                                        <li class="nav-item">
                                            <a class="nav-link @menuTextColor" asp-area="" asp-controller="Brand" asp-action="Index">Brands</a>
                                        </li>


                                        <li class="nav-item">
                                            <a class="nav-link @menuTextColor" asp-area="" asp-controller="ProductProfile" asp-action="Index">ProductProfiles</a>
                                        </li>



                                        <li class="nav-item">
                                            <a class="nav-link @menuTextColor" asp-area="" asp-controller="ProductGroup" asp-action="Index">Product Groups</a>
                                        </li>


                                    </ul>

                                </li>


                            }

                            <li class="nav-item">
                                <a class="nav-link @menuTextColor" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                        </ul>

                        <partial name="_LoginPartial" />


                    </div>
                </div>
            </nav>
        </header>
    </div>

    <div class="container">
        <main role="main" class="pb-3">


            <!--Success Dialog Start-->
            <div id="myModalSuccess" class="modal fade text-width:30%;" role="dialog">
                <div class="modal-dialog">
                    <div class="modal-content">

                        <div class="modal-header">
                            <h2>Information</h2>
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                        </div>

                        <div id="MyModalSuccessAlertBody" class="modal-body alert alert-success">
                            this is a modal body. our message will appear here.
                        </div>

                        <div class="modal-footer">
                            &nbsp;
                            <button type="button" class="btn btn-info" data-dismiss="modal">Close</button>
                        </div>

                    </div>
                </div>
            </div>
            <!--Success Dialog End-->
            <!--Error Dialog Start-->
            <div id="myModalError" class="modal fade text-width:30%;" role="dialog">
                <div class="modal-dialog">
                    <div class="modal-content">

                        <div class="modal-header">
                            <h2>Error</h2>
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                        </div>

                        <div id="MyModalErrorAlertBody" class="modal-body alert alert-danger">
                            this is a modal body. our message will appear here.
                        </div>

                        <div class="modal-footer">
                            &nbsp;
                            <button type="button" class="btn btn-info" data-dismiss="modal">Close</button>
                        </div>

                    </div>
                </div>
            </div>
            <!--Error Dialog End-->


            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" style="background:linear-gradient(to left,#28340B,#197696);">
        <div class="container @menuTextColor ">
            &copy; 2021 - Inventory - <a asp-area="" asp-controller="Home" asp-action="Privacy" class="@menuTextColor">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_bottomBar.cshtml
@using CodesByAniz.Tools;
@model PagerModel

@*style="background-color:black; border-radius:10px;  height:45px; color:white;"*@
<div class="container m-0 p-0 btn-group" style="background-color:lightgray; border-radius: 25px; height:45px;">

    <div class="col-4 btn-group p-1 m-1">
        <p>
            Showing @Model.StartRecord to @Model.EndRecord of @Model.TotalItems Rows
        </p>
    </div>



    <div class="col-3 btn-group justify-content-end">
        <span class="col-7 mt-2 p-0">
            Rows Per Page
        </span>

        <span class="col-5 p-1">
            <select class="form-control" id="pageSelector" asp-items="Model.GetPageSizes();"
                    onchange="ChangePageSize(this);">
            </select>
        </span>
    </div>



    <div class="col-4 btn-group justify-content-end mt-2">
        <p>
            Showing @Model.CurrentPage / @Model.TotalPages Pages
        </p>
    </div>


</div>

<script>
    function ChangePageSize(obj)
    {
        var controllerName = '@this.ViewContext.RouteData.Values["controller"].ToString()';
        window.location.href = "/" + controllerName + "/@Model.Action" + "?pageSize=" + obj.value + "&SearchText@Model.SearchText" + "&sortExpression=" + "@Model.SortExpression";
    }

</script>

Views/Shared/_topBar.cshtml
@using CodesByAniz.Tools;
@model PagerModel


<style>
    .page-link {
        color: black !important;
    }

    .page-item.active .page-link {
        z-index: 3;
        color: #fff;
        background-color: red !important;
        border-color: red;
    }
</style>

@*style="background-color:black; border-radius:10px; height:45px;"*@
<div class="container btn-group" style="background-color:lightgray; border-radius: 25px; height:45px;">

    <div class="col-4 p-0 justify-content-end mt-1">
        <form asp-action="index">
            <span class="btn-group">
                <input class="form-control" type="text"
                       name="SearchText"
                       value="@ViewBag.SearchText"
                       placeholder="Search Key" />

                <span class="ml-2 btn-group btn-danger" style="border-radius:10px;">
                    <i class="pl-2 fa fa-search align-self-center" aria-hidden="true"></i>
                    <input class="btn btn-sm font-weight-bold text-white"
                           type="submit" value="Search" />
                </span>



            </span>
        </form>
    </div>

    <div class="container mt-1">

        <ul class="pagination justify-content-end">

            @if (Model.CurrentPage > 1)
            {
                <li class="page-item">
                    <a class="page-link" asp-action="@Model.Action"
                       asp-route-pg="1"
                       asp-route-pageSize="@Model.PageSize"
                       asp-route-SearchText="@Model.SearchText"
                       asp-route-sortExpression="@Model.SortExpression">
                        First
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" asp-action="@Model.Action"
                       asp-route-pg="@(Model.CurrentPage-1)"
                       asp-route-pageSize="@Model.PageSize"
                       asp-route-SearchText="@Model.SearchText"
                       asp-route-sortExpression="@Model.SortExpression">
                        Previous
                    </a>
                </li>
            }



            @for (var pge = Model.StartPage; pge <= Model.EndPage; pge++)
            {
                <li class="page-item @(pge==Model.CurrentPage ?"active" : "")">
                    @if (pge != Model.CurrentPage)
                    {
                        <a class="page-link" asp-action="@Model.Action"
                           asp-route-pg="@pge"
                           asp-route-pageSize="@Model.PageSize"
                           asp-route-SearchText="@Model.SearchText"
                           asp-route-sortExpression="@Model.SortExpression">
                            @pge
                        </a>
                    }
                    else
                    {
                        <span class="page-link">@pge</span>
                    }
                </li>

            }



            @if (Model.CurrentPage < Model.TotalPages)
            {
                <li class="page-item">
                    <a class="page-link" asp-action="@Model.Action"
                       asp-route-pg="@(Model.CurrentPage+1)"
                       asp-route-pageSize="@Model.PageSize"
                       asp-route-SearchText="@Model.SearchText"
                       asp-route-sortExpression="@Model.SortExpression">
                        Next
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" asp-action="@Model.Action"
                       asp-route-pg="@(Model.TotalPages)"
                       asp-route-pageSize="@Model.PageSize"
                       asp-route-SearchText="@Model.SearchText"
                       asp-route-sortExpression="@Model.SortExpression">
                        Last
                    </a>
                </li>
            }




        </ul>
    </div>

</div>